project:
  type: website

website:
  title: "Stats_Progressed_Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: code/01-import.qmd
        text: Import
      - href: code/02-clean.qmd
        text: Clean
      - href: code/03-analyse.qmd
        text: Analyse
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




